# Generated by Django 5.0.6 on 2024-08-21 11:25

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBilligDetails',
            fields=[
                ('create_at', models.DateField(auto_created='2024-08-21T04:24:59.047572')),
                ('billingDetailId', models.UUIDField(auto_created=uuid.UUID('2b573a1f-b930-4b1e-bddd-f6134c4a4549'), primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('apartment', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=64)),
                ('payment_method', models.CharField(max_length=64)),
                ('payment_type', models.CharField(max_length=64)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('publishDate', models.DateField(auto_created=datetime.datetime(2024, 8, 21, 4, 24, 59, 47572))),
                ('commentId', models.UUIDField(auto_created=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReciept',
            fields=[
                ('create_at', models.DateTimeField(auto_created='2024-08-21T04:24:59.047572')),
                ('receiptId', models.UUIDField(auto_created=uuid.uuid1, primary_key=True, serialize=False)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('shippingPrice', models.IntegerField(default=0)),
                ('VATOnProduct', models.IntegerField(default=0)),
                ('grandTotalPriceOnProducts', models.IntegerField(default=0)),
                ('isRefund', models.BooleanField(default=False)),
                ('billing_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justyummy.customerbilligdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('orderDate', models.DateField(auto_created='2024-08-21T04:24:59.047572')),
                ('orderId', models.UUIDField(auto_created=uuid.uuid3, primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=64)),
                ('orderQuantity', models.IntegerField(default=1)),
                ('orderTotalPrice', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justyummy.customerreciept')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(auto_created=uuid.UUID('c50f7c0d-079d-4479-bb20-e59782893a48'), primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=64)),
                ('productCategory', models.CharField(choices=[('phone', 'Phone'), ('computer', 'Computer'), ('wristwatch', 'Wristwatch'), ('camera', 'Camera'), ('headphone', 'Headphone'), ('gaming', 'Gaming'), ('shoe, shoe', 'Shoe'), ('jewelry', 'Jewelry'), ('clothe', 'Clothe'), ('perfume', 'Perfume'), ('necklace', 'Necklace'), ('electronic', 'Electronic'), ('toy', 'Toy'), ('none', 'None')], default='none', max_length=32, unique=True)),
                ('isOnFlashSale', models.BooleanField(default=False)),
                ('productprice', models.IntegerField(default=0)),
                ('flashSalePrice', models.IntegerField(default=0)),
                ('isBestSelling', models.BooleanField(default=False)),
                ('orderRate', models.IntegerField(default=0)),
                ('productDesignation', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both'), ('children', 'Children'), ('baby', 'Baby'), ('all', 'All')], default='all', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 24, 59, 47572))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 24, 59, 47572))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
