# Generated by Django 5.0.6 on 2024-07-08 08:57

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('publishDate', models.DateField(auto_created=datetime.datetime(2024, 7, 8, 9, 57, 46, 614154))),
                ('commentId', models.UUIDField(auto_created=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReciept',
            fields=[
                ('create_at', models.DateTimeField(auto_created='2024-07-08T09:57:46.611590')),
                ('receiptId', models.UUIDField(auto_created=uuid.uuid1, primary_key=True, serialize=False)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('shippingPrice', models.IntegerField(default=0)),
                ('VATOnProduct', models.IntegerField(default=0)),
                ('grandTotalPriceOnProducts', models.IntegerField(default=0)),
                ('isRefund', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPurchasedOrders',
            fields=[
                ('purchaseDate', models.DateField(auto_created='2024-07-08T09:57:46.613125')),
                ('productPurchaseId', models.UUIDField(auto_created=uuid.uuid3, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('productPriceTotal', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justyummy.customerreciept')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(auto_created=uuid.UUID('6355bfac-2707-4bb6-85fe-589396170829'), primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=64)),
                ('productCategory', models.CharField(choices=[('phone', 'Phone'), ('computer', 'Computer'), ('smartWatch', 'smart watch'), ('camera', 'Camera'), ('headphone', 'Headphone'), ('gaming', 'Gaming'), ('none', 'None')], default='none', max_length=32, unique=True)),
                ('isOnFlashSale', models.BooleanField(default=False)),
                ('isBestSelling', models.BooleanField(default=False)),
                ('orderRate', models.IntegerField(default=0)),
                ('productDesignation', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both'), ('children', 'Children'), ('all', 'All')], default='all', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 7, 8, 9, 57, 46, 610539))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 7, 8, 9, 57, 46, 610539))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
