# Generated by Django 5.0.6 on 2024-08-21 11:30

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publishDate',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 21, 4, 30, 19, 323700)),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='billingDetailId',
            field=models.UUIDField(auto_created=uuid.UUID('13d95aa0-53bc-4c78-aae0-f88f979496e1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='create_at',
            field=models.DateField(auto_created='2024-08-21T04:30:19.323700'),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderDate',
            field=models.DateField(auto_created='2024-08-21T04:30:19.323700'),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(auto_created='2024-08-21T04:30:19.323700'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 30, 19, 323700)),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('952e267c-152b-440b-adf5-9f66fad16e5c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 30, 19, 323700)),
        ),
    ]
