# Generated by Django 5.0.6 on 2024-07-08 17:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flashSalePrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='productprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publishDate',
            field=models.DateField(auto_created=datetime.datetime(2024, 7, 8, 18, 34, 8, 740630)),
        ),
        migrations.AlterField(
            model_name='customerpurchasedorders',
            name='purchaseDate',
            field=models.DateField(auto_created='2024-07-08T18:34:08.740630'),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(auto_created='2024-07-08T18:34:08.740630'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 18, 34, 8, 740630)),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('0f5d4dfe-92f6-439f-a916-4950ed9d240a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 18, 34, 8, 740630)),
        ),
    ]
