# Generated by Django 5.0.6 on 2024-08-21 11:35

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0002_alter_comment_publishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publishDate',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 21, 4, 34, 59, 368673)),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='billingDetailId',
            field=models.UUIDField(auto_created=uuid.UUID('f2e4066a-185f-4d73-986c-bb74f15438cc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='create_at',
            field=models.DateField(default='2024-08-21T04:34:59.368673'),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderDate',
            field=models.DateField(default='2024-08-21T04:34:59.368673'),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(default='2024-08-21T04:34:59.368673'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 34, 59, 368673)),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('8d6a883f-f315-4f0c-9cf6-5c53ade15ab0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 4, 34, 59, 368673)),
        ),
    ]
