# Generated by Django 5.0.6 on 2024-07-19 14:48

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0003_alter_comment_publishdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='publishDate',
            field=models.DateField(auto_created=datetime.datetime(2024, 7, 19, 15, 47, 47, 27797)),
        ),
        migrations.AlterField(
            model_name='customerpurchasedorders',
            name='purchaseDate',
            field=models.DateField(auto_created='2024-07-19T15:47:47.026798'),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(auto_created='2024-07-19T15:47:47.025797'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 15, 47, 47, 24797)),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('dc12aa9c-a38d-4a1c-a574-00d2ba511fb0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 15, 47, 47, 24797)),
        ),
    ]
