# Generated by Django 5.0.6 on 2024-08-21 11:40

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0003_alter_comment_publishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publishDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 11, 40, 2, 53347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='billingDetailId',
            field=models.UUIDField(auto_created=uuid.UUID('31203335-3c25-48f3-b136-a095a4bb31a2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 11, 40, 2, 53347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 11, 40, 2, 53347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 11, 40, 2, 53347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 11, 40, 2, 53347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('92319c3d-2ee9-47a9-a92d-3badf9f88b1a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 11, 40, 2, 53347, tzinfo=datetime.timezone.utc)),
        ),
    ]
