# Generated by Django 5.0.6 on 2024-08-21 11:43

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0004_alter_comment_publishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publishDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='billingDetailId',
            field=models.UUIDField(auto_created=uuid.UUID('66464d46-f269-45f7-84e8-2b8ceb36c24a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 11, 43, 13, 188625, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('e9dcefb0-ecc7-4011-9b75-cdcfc32aefba'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
