# Generated by Django 5.0.6 on 2024-08-21 11:46

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0005_alter_comment_publishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(auto_created=uuid.UUID('01a06a88-6a3f-46a9-b686-afa6344b7407'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='billingDetailId',
            field=models.UUIDField(auto_created=uuid.UUID('2d5e3cef-ccd8-4eb6-87a8-429be5d07e97'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilligdetails',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2024, 8, 21, 11, 46, 13, 606034, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderId',
            field=models.UUIDField(auto_created=uuid.UUID('d60b204d-cdde-4488-a39f-d7a072698f6e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(auto_created=uuid.UUID('f2e75814-e0cd-463a-b939-65b99eb18a80'), primary_key=True, serialize=False),
        ),
    ]
