# Generated by Django 5.0.6 on 2024-08-21 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0007_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBillingDetails',
            fields=[
                ('billingDetailId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('apartment', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=64)),
                ('payment_method', models.CharField(max_length=64)),
                ('payment_type', models.CharField(max_length=64)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('c592b136-8025-490e-98d7-9b54f39cec8d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='receiptId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='billing_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justyummy.customerbillingdetails'),
        ),
        migrations.DeleteModel(
            name='CustomerBilligDetails',
        ),
    ]
