# Generated by Django 5.0.6 on 2024-08-21 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0008_customerbillingdetails_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('5ab0943a-5b14-4f3e-be87-a3c328b9a66c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='VATOnProduct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='shippingPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
