# Generated by Django 5.0.6 on 2024-08-21 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0009_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('38962fbe-96d8-4ef7-af8f-0fff33105c64'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='grandTotalPriceOnProducts',
            field=models.FloatField(default=0),
        ),
    ]
