# Generated by Django 5.0.6 on 2024-08-21 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0010_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('3bb45817-cd75-41cd-a47c-0ae9b7318960'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerreciept',
            name='grandTotalPriceOnProducts',
            field=models.FloatField(),
        ),
    ]
