# Generated by Django 5.0.6 on 2024-08-21 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0011_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('553f5959-ddc8-4a9c-9051-662d72c18925'), primary_key=True, serialize=False),
        ),
    ]
