# Generated by Django 5.0.6 on 2024-08-21 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0012_alter_comment_commentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
