# Generated by Django 5.0.6 on 2024-08-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0013_alter_comment_commentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='orderTotalPrice',
            field=models.FloatField(default=0),
        ),
    ]
