# Generated by Django 5.0.6 on 2024-08-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0014_alter_customerorders_ordertotalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='orderTotalPrice',
            field=models.CharField(max_length=24),
        ),
    ]
