# Generated by Django 5.0.6 on 2024-08-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justyummy', '0015_alter_customerorders_ordertotalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='orderName',
            field=models.CharField(max_length=1024),
        ),
    ]
